<a href="https://colab.research.google.com/github/dharshdk/DL/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0 #grey scale -

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)), #flatten - normalize
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2), #unwanted layers dropout
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.5748933 , -0.04638225,  0.4751154 , -0.185416  , -0.369858  ,
        -0.04075545,  0.4595998 ,  0.5383721 , -0.44058898, -0.6422392 ]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.15741998, 0.08457525, 0.14247112, 0.07359727, 0.06120115,
        0.08505249, 0.14027767, 0.15177453, 0.05702187, 0.04660858]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True) #loss function

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.4644866

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2955 - accuracy: 0.9150
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1435 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1064 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0870 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0739 - accuracy: 0.9766


313/313 - 1s - loss: 0.0761 - accuracy: 0.9768 - 1s/epoch - 4ms/step


[0.07610248774290085, 0.9768000245094299]